title = "Valley Top Repair Website"
baseURL = "http://www.valleytoprepair.com/"
languageCode = "en-us"
theme = "hugo-universal-theme"

[params]
  description = "Welcome to my website. Here you can find information about our services and how to contact us."
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3